secrets:
    ssh_key:
        file: ~/.ssh/id_rsa

services:
    php:
        secrets:
        -   source: ssh_key
            target: /var/www/.ssh/id_rsa
        environment:
            SSH_AUTH_SOCK: /ssh-agent
        volumes:
        - ${SSH_AUTH_SOCK}:/ssh-agent # Forward local machine SSH key to docker
        - /run/media/studea:/var/studea
        extra_hosts:
        - "studeav3.local:172.25.0.102"
        networks:
            default:
                ipv4_address: 172.25.0.102
        command: sh -c 'sudo /usr/sbin/apache2ctl -D FOREGROUND'