version: '3.8'

services:
    mariadb:
        image: mariadb:10.3.39
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        command:
            - "--default-authentication-plugin=mysql_native_password"
        tmpfs: /var/lib/mysql  # Plus rapide en CI

    mongo:
        image: mongo

    redis:
        image: redis

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
        environment:
            - discovery.type=single-node
            - transport.host=127.0.0.1
            - xpack.security.enabled=false
            - xpack.security.enrollment.enabled=false
            - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Limiter la mémoire en CI

    chrome:
        image: selenium/standalone-chrome:3.141.59
        shm_size: 2gb
        environment:
            - SCREEN_WIDTH=1920
            - SCREEN_HEIGHT=1080

    php:
        image: ${CI_REGISTRY_IMAGE}/php:latest
        networks:
            default:
                aliases:
                    - docker.local
        depends_on:
            - mariadb
            - chrome
            - mongo
            - redis
            - elasticsearch
        environment:
            - APP_ENV=test
            - BEHAT_BASE_URL=https://docker.local
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        # Pas de command, on va exécuter les commandes manuellement dans le script GitLab

networks:
    default:
